# Generated by Django 5.2 on 2025-04-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reciepe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciepe_name', models.CharField(max_length=250)),
                ('reciepe_desc', models.TextField()),
                ('reciepe_img', models.ImageField(upload_to='receipe')),
            ],
        ),
    ]
